# Generated by Django 5.0.1 on 2024-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatora', '0002_products_created_at_alter_customer_user_count_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
