# Generated by Django 5.0.1 on 2024-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatora', '0003_products_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='star',
            field=models.IntegerField(default=4),
        ),
    ]
