# Generated by Django 5.0.1 on 2024-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatora', '0005_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
