# Generated by Django 5.0.1 on 2024-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatora', '0007_remove_orders_product_remove_orders_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
