# Generated by Django 5.0.1 on 2024-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatora', '0008_orders_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_order',
            field=models.IntegerField(default=0),
        ),
    ]
